move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\app\shared\xpd.visualization\member-performance.directive.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\app\shared\xpd.visualization\member-performance.directive.scss
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\admin.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\admin.scss
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\angular.treeview.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\angular.treeview.scss
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\dhtmlxgantt.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\dhtmlxgantt.scss
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\dhtmlxgantt_broadway.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\dhtmlxgantt_broadway.scss
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\dmec-log.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\dmec-log.scss
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\hg-pallete.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\hg-pallete.scss
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\pallete.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\pallete.scss
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\reports.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\reports.scss
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\scrollbar.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\scrollbar.scss
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\xpd-visualization.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\xpd-visualization.scss
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\xpd.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\xpd.scss
