move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\admin\assets\css\dhtmlxgantt.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\admin\assets\css\dhtmlxgantt_broadway.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\admin\assets\css\reports.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\admin\assets\js\d3.min.js C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\admin\assets\js\dhtmlxgantt.js C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\admin.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\angular.treeview.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\dhtmlxgantt.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\dhtmlxgantt_broadway.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\dmec-log.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\hg-pallete.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\pallete.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\reports.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\xpd-visualization.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\xpd.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\css\README\README.md C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\favicon\favicon.ico C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\gif\gears-running.gif C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ico\favicon.ico C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ico\logo.ico C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\icon\logo.ico C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\icon\logo.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\js\d3.min.js C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\js\dhtmlxgantt.js C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\js\highcharts-more.js C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\js\highcharts.js C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\js\multicolor_series.js C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\bg.png\bg.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\checked-icon.png\checked-icon.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\drillship-status.png\drillship-status.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\file.png\file.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\folder-closed.png\folder-closed.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\folder.png\folder.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\gears-current.png\gears-current.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\hard-hat.png\hard-hat.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\imagem_acceleration.png\imagem_acceleration.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\logo.png\logo.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\member-1.png\member-1.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\member-2.png\member-2.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\member-3.png\member-3.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\member-4.png\member-4.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\member-5.png\member-5.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\member-6.png\member-6.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\member-slot-placeholder.png\member-slot-placeholder.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\ship-placeholder.png\ship-placeholder.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\team-icon.png\team-icon.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\teams-icon.png\teams-icon.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\worker-icon.png\worker-icon.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\png\xpd-logo.png\xpd-logo.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ttf\agency-fb.ttf\agency-fb.ttf C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\css\admin.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\css\dmec-log.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\css\hg-pallete.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\css\pallete.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\css\xpd.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\css\img\hard-hat.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\css\img\team-icon.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\css\img\teams-icon.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\css\img\worker-icon.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\fonts\agency-fb.ttf C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\img\drillship-status.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\img\gears-current.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\img\gears-running.gif C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\img\imagem_acceleration.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\img\member-slot-placeholder.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\img\ship-placeholder.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\img\xpd-logo.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\img\bravoteam\member-1.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\img\bravoteam\member-2.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\img\bravoteam\member-3.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\img\bravoteam\member-4.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\img\bravoteam\member-5.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\img\bravoteam\member-6.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\img\driller\bg.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\img\members\member-1.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\img\members\member-2.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\img\members\member-3.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\img\members\member-4.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\img\members\member-5.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\img\members\member-6.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\ng\angular.treeview\LICENSE C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\ng\angular.treeview\README.md C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\ng\angular.treeview\css\angular.treeview.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\ng\angular.treeview\img\checked-icon.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\ng\angular.treeview\img\file.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\ng\angular.treeview\img\folder-closed.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\ng\angular.treeview\img\folder.png C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\ng\xpd.timers\xpd-timers.worker.js C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\ng\xpd.visualization\d3-dmec-chart.worker.js C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
move C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\xpd-resources\ng\xpd.visualization\xpd-visualization.css C:\Users\RZX-PC03\Desktop\Projetos\tela-admin\src\assets\ 
